function createAssessmentModule(category) {
    const section = document.createElement('section');
    section.className = 'module assessment-module';
    section.id = 'assessmentModule';
    section.innerHTML = `
        <div class="assessment-container">
            <header class="assessment-header">
                <div><h1>Assignments</h1><p>Create, manage, monitor and track school assignments.</p></div>
                <div class="assessment-actions"><button class="assessment-btn assessment-btn-light" type="button" data-assessment-preview><i class="fas fa-eye"></i> Preview</button><button class="assessment-btn assessment-btn-primary" type="button" data-assessment-new><i class="fas fa-plus"></i> New Assignment</button></div>
            </header>
            <div class="assessment-card assessment-form" data-assessment-form>
                <div class="assessment-form-title"><div><h2>Create Assignment</h2><span>Enter assignment details below</span></div><button class="assessment-btn assessment-btn-small assessment-btn-dark" type="button" data-assessment-close><i class="fas fa-xmark"></i> Close</button></div>
                <form data-assessment-entry><div class="assessment-grid">
                    <div class="assessment-field"><label>Assignment Title *</label><input name="title" required placeholder="e.g. Mathematics Algebra Exercise"></div>
                    <div class="assessment-field"><label>Subject *</label><select name="subject" required><option value="">Select Subject</option><option>Mathematics</option><option>English</option><option>Science</option><option>Computer Science</option><option>Physics</option><option>Chemistry</option><option>Biology</option><option>Social Studies</option><option>Geography</option><option>History</option><option>Arabic</option><option>Other</option></select></div>
                    <div class="assessment-field"><label>Class / Grade *</label><select name="className" required><option value="">Select Class</option>${Array.from({length:12},(_,index)=>`<option>Grade ${index+1}</option>`).join('')}</select></div>
                    <div class="assessment-field"><label>Section</label><select name="section"><option>A</option><option>B</option><option>C</option><option>D</option><option>All Sections</option></select></div>
                    <div class="assessment-field"><label>Teacher *</label><input name="teacher" required placeholder="Teacher name"></div><div class="assessment-field"><label>Academic Year</label><input name="academicYear" value="2026/27"></div>
                    <div class="assessment-field"><label>Academic Period</label><select name="period"><option>Term 1</option><option>Term 2</option><option>Term 3</option><option>Semester 1</option><option>Semester 2</option></select></div><div class="assessment-field"><label>Assignment Type</label><select name="type"><option>Homework</option><option>Classwork</option><option>Project</option><option>Research</option><option>Quiz</option><option>Practical</option><option>Coursework</option></select></div>
                    <div class="assessment-field"><label>Assigned Date *</label><input type="date" name="assignedDate" required></div><div class="assessment-field"><label>Due Date *</label><input type="date" name="dueDate" required></div><div class="assessment-field"><label>Maximum Marks</label><input type="number" name="marks" value="100" min="1"></div><div class="assessment-field"><label>Priority</label><select name="priority"><option>Normal</option><option>High</option><option>Urgent</option></select></div>
                    <div class="assessment-field"><label>Status</label><select name="status"><option>Published</option><option>Draft</option><option>Pending</option><option>Closed</option></select></div><div class="assessment-field"><label>Submission Method</label><select name="submission"><option>Online</option><option>Physical</option><option>Online + Physical</option><option>Class Presentation</option></select></div><div class="assessment-field"><label>Attachment</label><input type="file" name="attachment"></div>
                    <div class="assessment-field full"><label>Assignment Instructions / Description</label><textarea name="description" placeholder="Enter assignment instructions, requirements and details..."></textarea></div><div class="assessment-field full"><label>Learning Objectives</label><textarea name="objectives" placeholder="What should students learn or demonstrate?"></textarea></div>
                </div><div class="assessment-form-actions"><button class="assessment-btn assessment-btn-dark" type="reset">Reset</button><button class="assessment-btn assessment-btn-light" type="button" data-assessment-close>Cancel</button><button class="assessment-btn assessment-btn-primary" type="submit"><i class="fas fa-floppy-disk"></i> Save Assignment</button></div></form>
            </div>
            <div class="assessment-card assessment-preview"><div class="assessment-preview-header" data-assessment-preview><h3><i class="fas fa-clipboard-list"></i> Assignment Preview</h3><span data-assessment-arrow>▼</span></div><div class="assessment-preview-content" data-assessment-preview-content><div class="assessment-sheet"><div class="assessment-sheet-top"><h2 data-preview="title">Mathematics Algebra Exercise</h2><div data-preview="subject">Mathematics</div><div class="assessment-meta"><span data-preview="className">Grade 8 - A</span><span data-preview="teacher">Teacher: Mr. Ahmed</span><span data-preview="type">Homework</span><span data-preview="period">Term 1</span></div></div><div class="assessment-sheet-body"><div class="assessment-preview-grid"><div class="assessment-info"><strong>Assigned Date</strong><span data-preview="assignedDate">24 Aug 2026</span></div><div class="assessment-info"><strong>Due Date</strong><span data-preview="dueDate">31 Aug 2026</span></div><div class="assessment-info"><strong>Maximum Marks</strong><span data-preview="marks">100</span></div><div class="assessment-info"><strong>Submission</strong><span data-preview="submission">Online</span></div></div><div class="assessment-preview-spacer"></div><div class="assessment-info"><strong>Description</strong><div data-preview="description">Complete the assigned algebra exercises and submit your answers before the deadline.</div></div><div class="assessment-preview-spacer"></div><div class="assessment-info"><strong>Learning Objectives</strong><div data-preview="objectives">Demonstrate understanding of algebraic expressions and problem solving.</div></div></div><div class="assessment-sheet-footer"><span>Assignment ID: <b data-preview="id">ASG-2026-001</b></span><span data-preview="status">Published</span></div></div></div></div>
            <div class="assessment-card assessment-table-card"><div class="assessment-table-header"><div><h2>Assignment Records</h2><span>Manage all assignments</span></div><input class="assessment-search" placeholder="Search assignments..." data-assessment-search></div><div class="assessment-table-wrap"><table class="assessment-table"><thead><tr><th>Assignment No.</th><th>Assignment</th><th>Subject</th><th>Class</th><th>Teacher</th><th>Assigned</th><th>Due Date</th><th>Marks</th><th>Submissions</th><th>Status</th><th>Actions</th></tr></thead><tbody data-assessment-table></tbody></table><div class="assessment-empty" data-assessment-empty>No assignments found.</div></div></div>
        </div>`;

    const form = section.querySelector('[data-assessment-entry]');
    const field = name => form.elements[name];
    const key = 'schoolAssignments';
    let records = JSON.parse(localStorage.getItem(key) || 'null') || [
        {id:'ASG-2026-001',title:'Algebra Exercise',subject:'Mathematics',className:'Grade 8',section:'A',teacher:'Mr. Ahmed',assignedDate:'2026-08-24',dueDate:'2026-08-31',marks:100,submissions:'28 / 32',status:'Published'},
        {id:'ASG-2026-002',title:'Science Research Project',subject:'Science',className:'Grade 9',section:'B',teacher:'Mrs. Sara',assignedDate:'2026-08-23',dueDate:'2026-09-05',marks:50,submissions:'17 / 30',status:'Pending'},
        {id:'ASG-2026-003',title:'English Essay',subject:'English',className:'Grade 7',section:'A',teacher:'Mr. John',assignedDate:'2026-08-20',dueDate:'2026-08-27',marks:100,submissions:'30 / 30',status:'Due Soon'}
    ];
    let counter = records.length + 1;
    const escape = value => String(value ?? '').replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[char]));
    const formatDate = value => value ? new Date(`${value}T00:00:00`).toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric'}) : '—';
    const badgeClass = status => status === 'Published' ? 'assessment-published' : status === 'Pending' ? 'assessment-pending' : status === 'Draft' ? 'assessment-draft' : 'assessment-late';
    const render = () => { const query = section.querySelector('[data-assessment-search]').value.toLowerCase(); const rows = records.filter(record => Object.values(record).join(' ').toLowerCase().includes(query)); section.querySelector('[data-assessment-table]').innerHTML = rows.map(record => `<tr><td>${escape(record.id)}</td><td><b>${escape(record.title)}</b></td><td>${escape(record.subject)}</td><td>${escape(record.className)} - ${escape(record.section)}</td><td>${escape(record.teacher)}</td><td>${formatDate(record.assignedDate)}</td><td>${formatDate(record.dueDate)}</td><td>${escape(record.marks)}</td><td>${escape(record.submissions || '0 / 0')}</td><td><span class="assessment-badge ${badgeClass(record.status)}">${escape(record.status)}</span></td><td><div class="assessment-row-actions"><button class="assessment-btn assessment-btn-small assessment-btn-dark" data-action="view" data-id="${escape(record.id)}">View</button><button class="assessment-btn assessment-btn-small assessment-btn-light" data-action="edit" data-id="${escape(record.id)}">Edit</button><button class="assessment-btn assessment-btn-small assessment-btn-danger" data-action="delete" data-id="${escape(record.id)}">Delete</button></div></td></tr>`).join(''); section.querySelector('[data-assessment-empty]').style.display = rows.length ? 'none' : 'block'; };
    const updatePreview = () => { const values = Object.fromEntries([...form.elements].filter(element => element.name).map(element => [element.name, element.value])); const preview = (name, value) => { const element = section.querySelector(`[data-preview="${name}"]`); if (element) element.textContent = value; }; preview('title',values.title || 'New Assignment'); preview('subject',values.subject || 'Subject'); preview('className',`${values.className || 'Class'} - ${values.section || 'A'}`); preview('teacher',`Teacher: ${values.teacher || 'Teacher'}`); preview('type',values.type || 'Homework'); preview('period',values.period || 'Term 1'); preview('marks',values.marks || '100'); preview('submission',values.submission || 'Online'); preview('description',values.description || 'Assignment description will appear here.'); preview('objectives',values.objectives || 'Learning objectives will appear here.'); preview('assignedDate',formatDate(values.assignedDate) || '24 Aug 2026'); preview('dueDate',formatDate(values.dueDate) || '31 Aug 2026'); preview('status',values.status || 'Published'); };
    const reset = () => { form.reset(); const today = new Date(); const due = new Date(today); due.setDate(today.getDate() + 7); field('assignedDate').value = today.toISOString().slice(0,10); field('dueDate').value = due.toISOString().slice(0,10); field('academicYear').value = '2026/27'; field('marks').value = '100'; updatePreview(); };
    const togglePreview = () => { const content = section.querySelector('[data-assessment-preview-content]'); const open = content.classList.toggle('is-open'); section.querySelector('[data-assessment-arrow]').textContent = open ? '▲' : '▼'; };
    section.querySelectorAll('[data-assessment-preview]').forEach(button => button.addEventListener('click', togglePreview));
    section.querySelector('[data-assessment-new]').addEventListener('click', () => { reset(); section.querySelector('[data-assessment-form]').classList.add('is-open'); section.querySelector('[data-assessment-form]').scrollIntoView({behavior:'smooth'}); field('title').focus(); });
    section.querySelectorAll('[data-assessment-close]').forEach(button => button.addEventListener('click', () => section.querySelector('[data-assessment-form]').classList.remove('is-open')));
    form.addEventListener('input', updatePreview); form.addEventListener('change', updatePreview); section.querySelector('[data-assessment-search]').addEventListener('input', render);
    form.addEventListener('reset', () => setTimeout(reset, 0));
    form.addEventListener('submit', event => { event.preventDefault(); const data = Object.fromEntries([...form.elements].filter(element => element.name && element.type !== 'file').map(element => [element.name, element.value])); const id = `ASG-2026-${String(counter++).padStart(3,'0')}`; records.unshift({...data,id,marks:Number(data.marks || 100),submissions:'0 / 0'}); localStorage.setItem(key,JSON.stringify(records)); render(); updatePreview(); section.querySelector('[data-assessment-form]').classList.remove('is-open'); alert('Assignment saved successfully.'); });
    section.querySelector('[data-assessment-table]').addEventListener('click', event => { const button = event.target.closest('[data-action]'); if (!button) return; const record = records.find(item => item.id === button.dataset.id); if (!record) return; if (button.dataset.action === 'delete') { if (confirm('Are you sure you want to delete this assignment?')) { records = records.filter(item => item.id !== record.id); localStorage.setItem(key,JSON.stringify(records)); render(); } return; } if (button.dataset.action === 'view') { alert(`Assignment Details\n\nAssignment: ${record.title}\nSubject: ${record.subject}\nClass: ${record.className} - ${record.section}\nTeacher: ${record.teacher}\nDue Date: ${formatDate(record.dueDate)}`); return; } Object.entries(record).forEach(([name,value]) => { if (field(name)) field(name).value = value; }); section.querySelector('[data-assessment-form]').classList.add('is-open'); updatePreview(); });
    reset(); render(); return section;
}
