function createSettingsModule() {
    const section = document.createElement('section');
    section.className = 'module settings-module hidden';
    section.id = 'settingsModule';
    section.innerHTML = `
        <div class="st-app"><div class="st-container">
            <header class="st-topbar"><div><h2>Settings</h2><p>System Department · Configure system preferences, security, notifications and integrations</p></div><div class="st-header-actions"><button class="st-btn st-light" type="button" data-st-reset><i class="fas fa-rotate-left"></i> Reset</button><button class="st-btn st-light" type="button" data-st-print><i class="fas fa-print"></i> Print / PDF</button><button class="st-btn st-primary" type="button" data-st-save><i class="fas fa-check"></i> Save Changes</button></div></header>
            <section class="st-cards"><article class="st-stat"><div><p>System Status</p><h3>Healthy</h3><small class="st-up">● All services online</small></div><i class="fas fa-circle-check st-icon st-green"></i></article><article class="st-stat"><div><p>Active Users</p><h3 data-st-user-count>248</h3><small class="st-up">▲ 12 this month</small></div><i class="fas fa-users st-icon st-blue"></i></article><article class="st-stat"><div><p>Security Score</p><h3>96%</h3><small class="st-up">Excellent</small></div><i class="fas fa-shield-halved st-icon st-purple"></i></article><article class="st-stat"><div><p>Notifications</p><h3>12</h3><small class="st-neutral">Configured</small></div><i class="fas fa-bell st-icon st-orange"></i></article><article class="st-stat"><div><p>Last Updated</p><h3 data-st-updated>—</h3><small class="st-up">Configuration synced</small></div><i class="fas fa-clock st-icon st-blue"></i></article></section>
            <div class="st-layout"><nav class="st-nav" aria-label="Settings sections"><div class="st-nav-title">Settings Menu</div>${[['general','General','fa-gear'],['appearance','Appearance','fa-circle-half-stroke'],['notifications','Notifications','fa-bell'],['security','Security','fa-shield-halved'],['users','User Management','fa-users'],['localization','Localization','fa-globe'],['integrations','Integrations','fa-plug'],['system','System','fa-server']].map(([key,label,icon],index)=>`<button type="button" class="st-nav-item${index===0?' active':''}" data-st-panel="${key}"><span class="st-nav-icon"><i class="fas ${icon}"></i></span>${label}</button>`).join('')}</nav>
            <main class="st-content">
                <section class="st-panel active" data-st-view="general"><header class="st-panel-head"><div><h3>General Settings</h3><p>Manage basic information and system-wide configuration.</p></div><span class="st-badge success">● Configuration Active</span></header><div class="st-panel-body"><div class="st-profile"><div class="st-avatar">ED</div><div class="st-profile-info"><strong>Education Management System</strong><small>Central system configuration · Local preview</small></div><span class="st-badge info">Production</span></div><div class="st-setting"><h4>Organization Information</h4><div class="st-form-grid"><label>Organization Name<input data-setting="orgName" value="Modern Education Academy"></label><label>System Name<input data-setting="systemName" value="Education Management System"></label><label>Organization Code<input data-setting="orgCode" value="MEA-001"></label><label>Academic Year<select data-setting="academicYear"><option>2026 - 2027</option><option>2027 - 2028</option><option>2028 - 2029</option></select></label><label>Administrator Email<input data-setting="adminEmail" type="email" value="admin@example.com"></label><label>Support Phone<input data-setting="supportPhone" value="+971 50 000 0000"></label><label class="st-full">Organization Address<textarea data-setting="orgAddress">United Arab Emirates</textarea></label></div></div><div class="st-setting"><h4>System Preferences</h4>${toggle('maintenanceMode','Enable Maintenance Mode','Temporarily restrict access while system maintenance is performed.')}${toggle('passwordReset','Allow Self-Service Password Reset','Allow users to reset their passwords without administrator assistance.',true)}${toggle('activityTracking','Enable Activity Tracking','Record user activities for auditing and security purposes.',true)}</div></div></section>
                <section class="st-panel" data-st-view="appearance"><header class="st-panel-head"><div><h3>Appearance</h3><p>Customize the look and feel of the system interface.</p></div></header><div class="st-panel-body"><div class="st-setting"><h4>Interface Preferences</h4><div class="st-form-grid"><label>Theme<select data-setting="theme"><option>Light</option><option>Dark</option><option>System Default</option></select></label><label>Primary Color<select data-setting="primaryColor"><option>Indigo</option><option>Blue</option><option>Emerald</option><option>Violet</option></select></label><label>Sidebar Style<select data-setting="sidebarStyle"><option>Expanded</option><option>Compact</option><option>Auto Collapse</option></select></label><label>Table Density<select data-setting="tableDensity"><option>Comfortable</option><option>Compact</option><option>Spacious</option></select></label></div></div><div class="st-setting"><h4>Interface Options</h4>${toggle('animations','Show Dashboard Animations','Enable smooth transitions and visual effects.',true)}${toggle('quickActions','Show Quick Actions','Display shortcut actions throughout the dashboard.',true)}${toggle('rememberFilters','Remember Table Filters','Keep filters and sorting preferences between sessions.',true)}</div></div></section>
                <section class="st-panel" data-st-view="notifications"><header class="st-panel-head"><div><h3>Notifications</h3><p>Control system alerts, emails and communication preferences.</p></div><span class="st-badge success">12 Rules Active</span></header><div class="st-panel-body"><div class="st-setting"><h4>Notification Channels</h4>${toggle('emailNotifications','Email Notifications','Send system alerts and important updates by email.',true)}${toggle('smsNotifications','SMS Notifications','Send urgent alerts and communication through SMS.',true)}${toggle('browserNotifications','Browser Notifications','Show real-time notifications inside the application.',true)}${toggle('weeklySummary','Weekly Summary','Receive a weekly system activity summary.')}</div><div class="st-setting"><h4>Alert Preferences</h4>${toggle('failedLoginAlerts','Failed Login Alerts','Notify administrators after suspicious login activity.',true)}${toggle('backupFailureAlerts','Backup Failure Alerts','Notify administrators when a scheduled backup fails.',true)}${toggle('downtimeAlerts','System Downtime Alerts','Notify administrators when critical services become unavailable.',true)}</div></div></section>
                <section class="st-panel" data-st-view="security"><header class="st-panel-head"><div><h3>Security Settings</h3><p>Configure authentication, passwords and account security.</p></div><span class="st-badge success">Security Score 96%</span></header><div class="st-panel-body"><div class="st-setting"><h4>Authentication</h4><div class="st-security-row"><i class="fas fa-shield-halved st-security-icon"></i><div><strong>Two-Factor Authentication</strong><small>Require an additional verification step for administrator accounts.</small></div><span class="st-badge success">Enabled</span><button type="button" class="st-btn st-light" data-st-toast="2FA settings are a local preview.">Configure</button></div><div class="st-security-row"><i class="fas fa-key st-security-icon"></i><div><strong>Password Policy</strong><small>Minimum 10 characters, uppercase, number and special character required.</small></div><span class="st-badge info">Strong</span><button type="button" class="st-btn st-light" data-st-password>Configure</button></div><label class="st-inline-setting">Session Timeout<select data-setting="sessionTimeout"><option>15 minutes</option><option selected>30 minutes</option><option>60 minutes</option><option>120 minutes</option></select></label></div><div class="st-setting"><h4>Security Controls</h4>${toggle('blockSuspiciousIps','Block Suspicious IP Addresses','Automatically block repeated suspicious authentication attempts.',true)}${toggle('forceHttps','Force HTTPS','Require encrypted connections throughout the application.',true)}${toggle('loginLogging','Login Activity Logging','Record successful and failed authentication attempts.',true)}</div></div></section>
                <section class="st-panel" data-st-view="users"><header class="st-panel-head"><div><h3>User Management</h3><p>Manage administrators, permissions and account access.</p></div><button type="button" class="st-btn st-primary" data-st-add-user><i class="fas fa-plus"></i> Add User</button></header><div class="st-table-wrap"><table class="st-table"><thead><tr><th>User</th><th>Role</th><th>Department</th><th>Last Login</th><th>Status</th><th>Actions</th></tr></thead><tbody data-st-users></tbody></table></div></section>
                <section class="st-panel" data-st-view="localization"><header class="st-panel-head"><div><h3>Localization</h3><p>Configure language, timezone, date and number formatting.</p></div></header><div class="st-panel-body"><div class="st-setting"><h4>Regional Preferences</h4><div class="st-form-grid"><label>Language<select data-setting="language"><option>English</option><option>Arabic</option><option>French</option><option>Urdu</option></select></label><label>Timezone<select data-setting="timezone"><option>Asia/Dubai (GMT+04:00)</option><option>Asia/Riyadh (GMT+03:00)</option><option>Europe/London (GMT+00:00)</option></select></label><label>Date Format<select data-setting="dateFormat"><option>DD/MM/YYYY</option><option>MM/DD/YYYY</option><option>YYYY-MM-DD</option></select></label><label>Time Format<select data-setting="timeFormat"><option>12 Hour</option><option>24 Hour</option></select></label><label>Currency<select data-setting="currency"><option>AED - UAE Dirham</option><option>USD - US Dollar</option><option>EUR - Euro</option><option>GBP - Pound Sterling</option></select></label><label>First Day of Week<select data-setting="weekStart"><option>Monday</option><option>Sunday</option><option>Saturday</option></select></label></div></div></div></section>
                <section class="st-panel" data-st-view="integrations"><header class="st-panel-head"><div><h3>Integrations</h3><p>Manage external services, API connections and system integrations.</p></div><button type="button" class="st-btn st-primary" data-st-add-integration><i class="fas fa-plus"></i> Add Integration</button></header><div class="st-panel-body"><div class="st-setting"><h4>Connected Services</h4><div class="st-integrations" data-st-integrations></div></div><div class="st-setting"><h4>API Access</h4><div class="st-api-key"><code data-st-api-key>sk_live_demo_••••••••••••••••••9F42</code><button class="st-btn st-light" type="button" data-st-copy>Copy</button><button class="st-btn st-danger" type="button" data-st-regenerate>Regenerate</button></div><small class="st-help">Demo key only. This preview does not connect to external services.</small></div></div></section>
                <section class="st-panel" data-st-view="system"><header class="st-panel-head"><div><h3>System Configuration</h3><p>Manage application behavior, backups and system maintenance.</p></div></header><div class="st-panel-body"><div class="st-setting"><h4>System Operations</h4>${toggle('automaticBackups','Automatic Backups','Run scheduled system backups automatically.',true)}${toggle('automaticUpdates','Automatic Updates','Install approved application updates automatically.',true)}${toggle('errorReporting','Error Reporting','Send anonymous technical error information to administrators.',true)}</div><div class="st-setting"><h4>System Information</h4><div class="st-form-grid"><label>Application Version<input value="v4.8.2" readonly></label><label>Database Version<input value="MySQL 8.0" readonly></label><label>Environment<input value="Local prototype" readonly></label><label>Server Status<input value="Preview only" readonly></label></div></div><div class="st-danger-zone"><strong>⚠ Danger Zone</strong><div><p>These actions are local preview controls and will not affect a live system.</p><button class="st-btn st-danger" type="button" data-st-clear-cache>Clear System Cache</button><button class="st-btn st-danger" type="button" data-st-reset-all>Reset All Settings</button></div></div></div></section>
            </main></div><div class="st-toast" role="status" aria-live="polite" data-st-toast></div>
            <div class="st-overlay" data-st-user-overlay><section class="st-modal" role="dialog" aria-modal="true" aria-labelledby="st-user-title"><header><h3 id="st-user-title">Add System User</h3><button type="button" data-st-close aria-label="Close">&times;</button></header><form data-st-user-form><div class="st-form-grid"><label>Full Name<input name="name" required></label><label>Email<input name="email" type="email" required></label><label>Role<select name="role"><option>Super Admin</option><option>System Admin</option><option>IT Support</option><option>Viewer</option></select></label><label>Department<select name="department"><option>System</option><option>Administration</option><option>Finance</option><option>Communication</option><option>HR</option><option>Academic</option></select></label><label>Status<select name="status"><option>Active</option><option>Suspended</option></select></label></div><footer><button class="st-btn st-light" type="button" data-st-close>Cancel</button><button class="st-btn st-primary" type="submit">Add User</button></footer></form></section></div>
            <div class="st-overlay" data-st-integration-overlay><section class="st-modal" role="dialog" aria-modal="true" aria-labelledby="st-integration-title"><header><h3 id="st-integration-title">Add Integration</h3><button type="button" data-st-close aria-label="Close">&times;</button></header><form data-st-integration-form><div class="st-form-grid"><label>Integration Name<input name="name" required placeholder="e.g. Payment Gateway"></label><label>Service Type<select name="type"><option>Email</option><option>SMS</option><option>Cloud Storage</option><option>Payment</option><option>API</option></select></label><label class="st-full">Endpoint / API URL<input name="url" type="url" placeholder="https://api.example.com"></label></div><footer><button class="st-btn st-light" type="button" data-st-close>Cancel</button><button class="st-btn st-primary" type="submit">Connect</button></footer></form></section></div>
        </div>`;
    const q = selector => section.querySelector(selector);
    const storageKey = 'schoolSystemSettings';
    const usersKey = 'schoolSystemSettingsUsers';
    const integrationsKey = 'schoolSystemSettingsIntegrations';
    const defaults = { orgName: 'Modern Education Academy', systemName: 'Education Management System', orgCode: 'MEA-001', academicYear: '2026 - 2027', adminEmail: 'admin@example.com', supportPhone: '+971 50 000 0000', orgAddress: 'United Arab Emirates', theme: 'Light', primaryColor: 'Indigo', sidebarStyle: 'Expanded', tableDensity: 'Comfortable', sessionTimeout: '30 minutes', language: 'English', timezone: 'Asia/Dubai (GMT+04:00)', dateFormat: 'DD/MM/YYYY', timeFormat: '12 Hour', currency: 'AED - UAE Dirham', weekStart: 'Monday', passwordReset: true, activityTracking: true, animations: true, quickActions: true, rememberFilters: true, emailNotifications: true, smsNotifications: true, browserNotifications: true, weeklySummary: false, failedLoginAlerts: true, backupFailureAlerts: true, downtimeAlerts: true, blockSuspiciousIps: true, forceHttps: true, loginLogging: true, automaticBackups: true, automaticUpdates: true, errorReporting: true, maintenanceMode: false };
    const seedUsers = [{ name: 'Ahmed Khan', email: 'ahmed.khan@example.com', role: 'Super Admin', department: 'System', lastLogin: 'Today · 05:42 PM', status: 'Active' }, { name: 'Sara Ali', email: 'sara.ali@example.com', role: 'System Admin', department: 'System', lastLogin: 'Today · 03:18 PM', status: 'Active' }, { name: 'Omar Hassan', email: 'omar.hassan@example.com', role: 'IT Support', department: 'IT Support', lastLogin: 'Yesterday · 08:25 PM', status: 'Suspended' }];
    const esc = value => String(value ?? '').replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#039;' }[char]));
    const read = (key, fallback) => { try { const value = JSON.parse(localStorage.getItem(key)); return value ?? fallback; } catch { return fallback; } };
    let settings = { ...defaults, ...read(storageKey, {}) };
    let users = read(usersKey, seedUsers);
    let integrations = read(integrationsKey, [{ name: 'Email Service', detail: 'SMTP · smtp.example.com · Port 587', status: 'Connected', type: 'Email' }, { name: 'SMS Gateway', detail: 'Primary SMS provider · Demo connection', status: 'Connected', type: 'SMS' }, { name: 'Cloud Storage', detail: 'Backup storage · Preview only', status: 'Attention', type: 'Cloud Storage' }]);
    let toastTimer;
    const toast = message => { const node = q('[data-st-toast]'); node.textContent = message; node.classList.add('show'); clearTimeout(toastTimer); toastTimer = setTimeout(() => node.classList.remove('show'), 2600); };
    function renderUsers() { q('[data-st-users]').innerHTML = users.map((user,index) => `<tr><td><strong>${esc(user.name)}</strong><small>${esc(user.email)}</small></td><td><span class="st-badge info">${esc(user.role)}</span></td><td>${esc(user.department)}</td><td>${esc(user.lastLogin || 'Not logged in')}</td><td><span class="st-badge ${user.status==='Active'?'success':'warning'}">${esc(user.status)}</span></td><td><button class="st-icon-btn" type="button" title="Reset password" data-st-user-action="password" data-index="${index}"><i class="fas fa-key"></i></button><button class="st-icon-btn" type="button" title="Toggle status" data-st-user-action="toggle" data-index="${index}"><i class="fas fa-user-check"></i></button></td></tr>`).join(''); q('[data-st-user-count]').textContent = String(248 + Math.max(0, users.length - seedUsers.length)); }
    function renderIntegrations() { q('[data-st-integrations]').innerHTML = integrations.map((item,index) => `<div class="st-security-row"><i class="st-security-icon fas ${item.type==='Email'?'fa-envelope':item.type==='SMS'?'fa-comment-sms':item.type==='Cloud Storage'?'fa-cloud':'fa-plug'}"></i><div><strong>${esc(item.name)}</strong><small>${esc(item.detail || `${item.type} · Local preview`)}</small></div><span class="st-badge ${item.status==='Connected'?'success':'warning'}">${esc(item.status)}</span><button class="st-btn st-light" type="button" data-st-integration-action="configure" data-index="${index}">Configure</button><button class="st-icon-btn" type="button" aria-label="Remove ${esc(item.name)}" data-st-integration-action="remove" data-index="${index}"><i class="fas fa-trash"></i></button></div>`).join(''); }
    function closeOverlays() { section.querySelectorAll('.st-overlay.show').forEach(overlay => overlay.classList.remove('show')); }
    function loadSettings() { section.querySelectorAll('[data-setting]').forEach(input => { const value = settings[input.dataset.setting]; if (input.type === 'checkbox') input.checked = Boolean(value); else if (value !== undefined) input.value = value; }); }
    loadSettings(); renderUsers(); renderIntegrations();
    q('[data-st-updated]').textContent = read(storageKey + ':updated', '5m');
    section.addEventListener('click', event => {
        const button = event.target.closest('button'); if (!button) return;
        if (button.dataset.stPanel) { section.querySelectorAll('[data-st-panel]').forEach(item => item.classList.toggle('active', item === button)); section.querySelectorAll('[data-st-view]').forEach(panel => panel.classList.toggle('active', panel.dataset.stView === button.dataset.stPanel)); return; }
        if (button.hasAttribute('data-st-save')) { section.querySelectorAll('[data-setting]').forEach(input => { settings[input.dataset.setting] = input.type === 'checkbox' ? input.checked : input.value; }); localStorage.setItem(storageKey, JSON.stringify(settings)); const stamp = new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }); localStorage.setItem(storageKey + ':updated', stamp); q('[data-st-updated]').textContent = stamp; toast('Settings saved in this browser.'); return; }
        if (button.hasAttribute('data-st-reset') || button.hasAttribute('data-st-reset-all')) { if (!confirm('Reset saved settings to their default values?')) return; settings = { ...defaults }; loadSettings(); localStorage.removeItem(storageKey); localStorage.removeItem(storageKey + ':updated'); q('[data-st-updated]').textContent = '—'; toast('Settings reset to defaults.'); return; }
        if (button.hasAttribute('data-st-print')) { window.print(); return; }
        if (button.hasAttribute('data-st-add-user')) { q('[data-st-user-overlay]').classList.add('show'); return; }
        if (button.hasAttribute('data-st-add-integration')) { q('[data-st-integration-overlay]').classList.add('show'); return; }
        if (button.hasAttribute('data-st-close')) { button.closest('.st-overlay').classList.remove('show'); return; }
        if (button.hasAttribute('data-st-password')) { toast('Password policy controls are available in this local preview.'); return; }
        if (button.hasAttribute('data-st-copy')) { navigator.clipboard?.writeText(q('[data-st-api-key]').textContent).then(() => toast('Demo key copied.')).catch(() => toast('Clipboard access is unavailable.')); return; }
        if (button.hasAttribute('data-st-regenerate')) { if (!confirm('Generate a new demo key for this browser preview?')) return; q('[data-st-api-key]').textContent = 'sk_live_demo_' + crypto.randomUUID().replaceAll('-', '').slice(0, 16).toUpperCase(); toast('Demo key regenerated locally.'); return; }
        if (button.hasAttribute('data-st-clear-cache')) { toast('No application cache is connected in this preview.'); return; }
        if (button.hasAttribute('data-st-user-action')) { const user = users[Number(button.dataset.index)]; if (!user) return; if (button.dataset.stUserAction === 'toggle') { user.status = user.status === 'Active' ? 'Suspended' : 'Active'; localStorage.setItem(usersKey, JSON.stringify(users)); renderUsers(); toast(`${user.name} is now ${user.status.toLowerCase()}.`); } else toast(`Password reset action for ${user.name} is a preview only.`); return; }
        if (button.hasAttribute('data-st-integration-action')) { const index = Number(button.dataset.index); if (button.dataset.stIntegrationAction === 'remove') { integrations.splice(index,1); localStorage.setItem(integrationsKey, JSON.stringify(integrations)); renderIntegrations(); toast('Integration removed from this preview.'); } else toast('Integration configuration is a local preview.'); return; }
        if (button.closest('.st-overlay') && event.target === button.closest('.st-overlay')) closeOverlays();
    });
    q('[data-st-user-form]').addEventListener('submit', event => { event.preventDefault(); const data = Object.fromEntries(new FormData(event.currentTarget)); users.unshift({ ...data, lastLogin: 'Not logged in' }); localStorage.setItem(usersKey, JSON.stringify(users)); event.currentTarget.reset(); closeOverlays(); renderUsers(); toast('User added to this browser preview.'); });
    q('[data-st-integration-form]').addEventListener('submit', event => { event.preventDefault(); const data = Object.fromEntries(new FormData(event.currentTarget)); integrations.unshift({ name: data.name, type: data.type, detail: data.url || `${data.type} · Local preview`, status: 'Attention' }); localStorage.setItem(integrationsKey, JSON.stringify(integrations)); event.currentTarget.reset(); closeOverlays(); renderIntegrations(); toast('Integration saved locally; no external connection was made.'); });
    section.querySelectorAll('.st-overlay').forEach(overlay => overlay.addEventListener('click', event => { if (event.target === overlay) overlay.classList.remove('show'); }));
    return section;
}
function toggle(name, title, description, checked = false) { return `<div class="st-toggle-row"><div><strong>${title}</strong><small>${description}</small></div><label class="st-switch"><input data-setting="${name}" type="checkbox"${checked ? ' checked' : ''}><span></span></label></div>`; }
